services:
  node1:
    build: .
    image: mpi-node:latest
    container_name: node1
    privileged: true
    environment:
      NODE_ROLE: server
    volumes:
      - nfs-data:/mnt/cluster
    networks:
      my-red:
        ipv4_address: 172.30.0.11

  node2:
    image: mpi-node:latest
    container_name: node2
    privileged: true
    environment:
      NODE_ROLE: client
      NFS_SERVER: 172.30.0.11
    depends_on:
      - node1
    networks:
      my-red:
        ipv4_address: 172.30.0.12

  node3:
    image: mpi-node:latest
    container_name: node3
    privileged: true
    environment:
      NODE_ROLE: client
      NFS_SERVER: 172.30.0.11
    depends_on:
      - node1
    networks:
      my-red:
        ipv4_address: 172.30.0.13

volumes:
  nfs-data:

networks:
  my-red:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
